//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrisetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int ADDRESS_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual user user { get; set; }
    }
}
