//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrisetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camiseta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public camiseta()
        {
            this.estampa = new HashSet<estampa>();
            this.factura = new HashSet<factura>();
            this.file = new HashSet<file>();
        }
    
        public int CAMISETA_ID { get; set; }
        public string MATERIAL { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] URL_CAMISETA { get; set; }
        public string VALOR { get; set; }
        public string NOMBRE { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> TEXTO_ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
    
        public virtual texto texto { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estampa> estampa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> file { get; set; }
    }
}
