//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrisetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estampa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public estampa()
        {
            this.factura = new HashSet<factura>();
            this.file = new HashSet<file>();
        }
    
        public int ESTAMPA_ID { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public byte[] URL_ESTAMPA { get; set; }
        public string RATING { get; set; }
        public string PRECIO { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> CAMISETA_ID { get; set; }
        public Nullable<int> TEMA_ID { get; set; }
    
        public virtual camiseta camiseta { get; set; }
        public virtual user user { get; set; }
        public virtual tema tema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<file> file { get; set; }
    }
}
