//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrisetas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class file
    {
        public int FILE_ID { get; set; }
        public byte[] CONTENT { get; set; }
        public string DESCRIPTION { get; set; }
        public string NAME { get; set; }
        public string PATH { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<int> CAMISETA_ID { get; set; }
        public Nullable<int> ESTAMPA_ID { get; set; }
        public Nullable<int> TEMA_ID { get; set; }
    
        public virtual camiseta camiseta { get; set; }
        public virtual estampa estampa { get; set; }
        public virtual tema tema { get; set; }
        public virtual user user { get; set; }
    }
}
