//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fabrisetas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fabricetasEntities : DbContext
    {
        public fabricetasEntities()
            : base("name=fabricetasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<camiseta> camiseta { get; set; }
        public virtual DbSet<estampa> estampa { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<file> file { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<tema> tema { get; set; }
        public virtual DbSet<texto> texto { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
