//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppli.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int FACTURA_ID { get; set; }
        public string NUMBER { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string ITEM_PRICE { get; set; }
        public string TOTAL_PRICE { get; set; }
        public Nullable<int> CAMISETA_ID { get; set; }
        public Nullable<int> TEMA_ID { get; set; }
        public Nullable<int> ESTAMPA_ID { get; set; }
    
        public virtual camiseta camiseta { get; set; }
        public virtual estampa estampa { get; set; }
        public virtual tema tema { get; set; }
    }
}
