//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppli.datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class prueba1
    {
        public int prueba1_id { get; set; }
        public string prueba1_nombre { get; set; }
    }
}
